const publicModel = (filename) => encodeURI(`/assets/3D models/${filename}`)
const BUNDLE_MODEL = publicModel('low_poly_furnitures_full_bundle.glb')

export const FURNITURE_CATALOG = [
  {
    id: 'opening-door',
    name: 'Interior Door',
    category: 'Openings',
    width: 0.9,
    depth: 0.2,
    height: 2.1,
    color: '#E1D1BF',
    icon: 'door',
    elementType: 'door',
    description: 'Wall-mounted opening with swing guide.',
  },
  {
    id: 'opening-window',
    name: 'Window',
    category: 'Openings',
    width: 1.2,
    depth: 0.2,
    height: 1.2,
    color: '#B6CBD9',
    icon: 'window',
    elementType: 'window',
    description: 'Window opening with outside-view preview.',
  },
  {
    id: 'furniture-4',
    name: 'Bed 1',
    category: 'Beds',
    width: 0.94,
    depth: 1.2,
    height: 0.61,
    color: '#E6E0D8',
    model: BUNDLE_MODEL,
    modelNode: 'Object_10',
    modelScale: 1.0,
    icon: 'bed',
    description: 'Bed 1 from bundle',
  },
  {
    id: 'furniture-21',
    name: 'Bed 2',
    category: 'Beds',
    width: 0.94,
    depth: 1.05,
    height: 0.79,
    color: '#C9A48B',
    model: BUNDLE_MODEL,
    modelNode: 'Object_44',
    modelScale: 1.0,
    icon: 'bed',
    description: 'Bed 2 from bundle',
  },
  {
    id: 'furniture-23',
    name: 'Bed 3',
    category: 'Beds',
    width: 1.1,
    depth: 1.07,
    height: 0.53,
    color: '#B08A6C',
    model: BUNDLE_MODEL,
    modelNode: 'Object_48',
    modelScale: 1.0,
    icon: 'bed',
    description: 'Bed 3 from bundle',
  },
  {
    id: 'furniture-6',
    name: 'TV Stand',
    category: 'Living',
    width: 0.3,
    depth: 1.32,
    height: 1.28,
    color: '#9C5B2B',
    model: BUNDLE_MODEL,
    modelNode: 'Object_14',
    modelScale: 1.0,
    icon: 'desk',
    description: 'TV Stand from bundle',
  },
  {
    id: 'furniture-11',
    name: 'Single Sofa',
    category: 'Seating',
    width: 0.89,
    depth: 0.8,
    height: 0.74,
    color: '#6F6A66',
    model: BUNDLE_MODEL,
    modelNode: 'Object_24',
    modelScale: 1.0,
    icon: 'sofa',
    description: 'Single Sofa from bundle',
  },
  {
    id: 'furniture-12',
    name: 'Chair',
    category: 'Seating',
    width: 0.6,
    depth: 0.67,
    height: 0.52,
    color: '#8B7763',
    model: BUNDLE_MODEL,
    modelNode: 'Object_26',
    modelScale: 1.0,
    icon: 'chair',
    description: 'Chair from bundle',
  },
  {
    id: 'furniture-13',
    name: 'Sofa 1',
    category: 'Seating',
    width: 0.8,
    depth: 2.13,
    height: 0.71,
    color: '#4C5A63',
    model: BUNDLE_MODEL,
    modelNode: 'Object_28',
    modelScale: 1.0,
    icon: 'sofa',
    description: 'Sofa 1 from bundle',
  },
  {
    id: 'furniture-18',
    name: 'Sofa 2',
    category: 'Seating',
    width: 1.8,
    depth: 0.77,
    height: 0.73,
    color: '#6C5F5B',
    model: BUNDLE_MODEL,
    modelNode: 'Object_38',
    modelScale: 1.0,
    icon: 'sofa',
    description: 'Sofa 2 from bundle',
  },
  {
    id: 'furniture-22',
    name: 'Single Closet',
    category: 'Storage',
    width: 0.29,
    depth: 0.65,
    height: 1.06,
    color: '#C9A47A',
    model: BUNDLE_MODEL,
    modelNode: 'Object_46',
    modelScale: 1.0,
    icon: 'bookshelf',
    description: 'Single Closet from bundle',
  },
  {
    id: 'furniture-27',
    name: 'Double Closet',
    category: 'Storage',
    width: 0.4,
    depth: 0.98,
    height: 1.06,
    color: '#D0A06A',
    model: BUNDLE_MODEL,
    modelNode: 'Object_56',
    modelScale: 1.0,
    icon: 'bookshelf',
    description: 'Double Closet from bundle',
  },
  {
    id: 'furniture-33',
    name: 'Mirror Table',
    category: 'Bedroom',
    width: 0.26,
    depth: 0.6,
    height: 0.95,
    color: '#C97C5D',
    model: BUNDLE_MODEL,
    modelNode: 'Object_68',
    modelScale: 1.0,
    icon: 'side-table',
    description: 'Mirror Table from bundle',
  },
]
